context("Generate identicons")
test_that("Check if seed repeatable",{
  expect_equal(generateIdenticon('abcde'),generateIdenticon('abcde'))
  expect_equal(generateIdenticon(12345),generateIdenticon(12345))
  expect_false(all(mapply(identical,generateIdenticon(12345),generateIdenticon(123456))))
  expect_false(all(mapply(identical,generateIdenticon('abc'),generateIdenticon('abd'))))
})
test_that("Check if nSquare returned appropriately",{
  expect_equal(generateIdenticon('abcde',nSquare=5)$nSquare,5)
  expect_equal(generateIdenticon('abcde',nSquare=4)$nSquare,4)
  expect_equal(generateIdenticon('abcde',nSquare=3)$nSquare,3)
  expect_equal(generateIdenticon('abcde',nSquare=2)$nSquare,2)
  expect_equal(generateIdenticon('abcde',nSquare=1)$nSquare,1)
  expect_equal(generateIdenticon('abcde',nSquare=5)$nSquare,5)
  expect_equal(generateIdenticon('abcde',nSquare=4)$nSquare,4)
  expect_equal(generateIdenticon('abcde',nSquare=3)$nSquare,3)
  expect_equal(generateIdenticon('abcde',nSquare=2)$nSquare,2)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=1)$type),1)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=2)$type),1)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=3)$type),4)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=4)$type),4)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=5)$type),9)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=1)$centers),1)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=2)$centers),4)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=3)$centers),9)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=4)$centers),16)
  expect_equal(nrow(generateIdenticon('abcde',nSquare=5)$centers),25)
})

test_that("Check if plot errors",{
  expect_silent(plotIdenticon(seed='abcde'))
  expect_silent(plotIdenticon(seed=12345))
  expect_silent(plotIdenticon(generateIdenticon(seed=12345),col='blue',back='red'))
})
